### ISSUE TITLE
JUnitReporter xml-file should contain console printout (puts) for every testcase.

### ISSUE THREAD

**Issue by kimiffx** [minitest-reporters/minitest-reporters#202]
JUnitReporter xml-file should contain console printout (puts) for every testcase. Then this gem will be very usable in Jenkins ! ( ci_reporter do this already )

**Comment by os97673** [comment]
It would be very helpful if you'd provide example of suggested output.

**Comment by kimiffx** [comment]
I think that just adding <system-out>My prints...</system-out> after testcases will be fine.
There's some sort of spec in http://llg.cubic.org/docs/junit/

**Comment by kimiffx** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TC_test_junit_xml" skipped="0" failures="0" errors="0" tests="2" assertions="1" time="0.00012403699929564027">
  <testcase name="test_01" classname="TC_test_junit_xml" assertions="0" time="9.968599988496862e-05">
	<system-out>
	Some prints...
	</system-out>
  </testcase>
  <testcase name="test_02" classname="TC_test_junit_xml" assertions="1" time="2.4350999410671648e-05">
	<system-out>
	Some other prints...
	</system-out>  
  </testcase>
</testsuite>`

**Comment by os97673** [comment]
Thank you for clarification.  Looks like a good idea.

**Comment by kimiffx** [comment]
Any timetable about this ? Will next version of reporter include this ?

**Comment by os97673** [comment]
no estimations, but PR is welcome ;)

**Comment by itsliamegan** [comment]
Hi @kimiffx! If this is still an important feature for you, please open a PR and we'll give it a look 👍
