### ISSUE TITLE
No way to pass color options to DefaultReporter from ENV variable

### ISSUE THREAD

**Issue by partydrone** [minitest-reporters/minitest-reporters#279]
When defining the reporter using `MINITEST_REPORTER` environment variable, there is no way to pass any options (e.g. `color: true`). I noticed this in `default_reporter.rb`:

```ruby
      def color?
        return @color if defined?(@color)
        @color = @options.fetch(:color) do
          io.tty? && (
            ENV["TERM"] =~ /^screen|color/ ||
            ENV["EMACS"] == "t"
          )
        end
      end
```

My OS already sets `TERM=xterm`. Is `xterm` safe to add to the regex, or is there some other way to turn on color when setting the default reporter using the environment variable?

**Comment by barrettkingram** [comment]
There's no way to pass this option directly, but you would probably be fine setting `TERM=xterm-256color`. It seems it may not be safe to assume `xterm` always indicates color support ([link](https://unix.stackexchange.com/a/23789)).

I wouldn't be opposed to adding another environment variable like `MINITEST_REPORTERS_COLORS` to enable colors if it would be useful and changing `TERM` isn't an option.
