### ISSUE TITLE
MeanTimeReporter seems to count fails too

### ISSUE THREAD

**Issue by rubydesign** [minitest-reporters/minitest-reporters#289]
Hi,
so with the latest version i am trying to find out my slowest tests. And that works great, thanks!

But i just mistyped and got a fail, running with guard. Since the test is like 2 seconds and the fail 0.002, once i got it running, the cumulative stats are seriously off. So i have to restart guard and run the whole suite to get see if the test i am working on is still in the worst 10.

Not a biggie, just would be nice. I think it's just a matter of not counting the fails.
With an ok i could have a crack at it myself.

**Comment by os97673** [comment]
The reporter provide not only average time but also time for the latest run.  Do you suggest to print that last/current run was .002 and show average 2.0?  It will be also misleading.
I'm not saying I like current behavior but I'm inviting to discuss how do we want to handle such situations.

**Comment by rubydesign** [comment]
Hi Oleg,
my suggestion is to just not count the times when the test fails.
Those times are not representative.

**Comment by os97673** [comment]
As you can see in [the comment](https://github.com/kern/minitest-reporters/blob/master/lib/minitest/reporters/mean_time_reporter.rb#L273-L274) the reporter is supposed to provide more "last time".  What you'd suggest for this?

**Comment by rubydesign** [comment]
Yes, i understand the logic there. And maybe i get your point.

I looked at the code a bit and it seems, that by the time you report, it is too late.
For my suggestion to work, you would have to not record the failed time.

in code that would be along the lines of

>     def record(test)
>       super unless test.failure?
>     end

**Comment by itsliamegan** [comment]
Hi @rubydesign! If you still think not measuring failure times is valuable, feel free to open a PR with the option to opt-out of it. That way, you can have the behavior you find more useful, but we won't break people's existing expectations of how this reporter works
