### ISSUE TITLE
Reporters don't include describe block as prefix for name

### ISSUE THREAD

**Issue by inspire22** [minitest-reporters/minitest-reporters#295]
I've tried wandering through the source of minitest-reporters & the default minitest reporter source, but I can't figure out how the default test-unit shows this while custom reporters don't.  Any tips what variable I should be including?

minitest default response, shows "add" as a prefix (this test is defined inside a describe "add" do block).
```
1) Failure:
add#test_0002_post invalid billing [/test.rb:184]:
Expected /blank/ to match nil.
```

minitest-reporter just shows test name:
```
   1) post invalid billing
      Expected false to be truthy.
            rails test  test.rb:206
```
Thanks!

**Comment by itsliamegan** [comment]
Could you provide some more detail on this? What does your test look like? What reporter are you using?

**Comment by inspire22** [comment]
Sorry, haven't used it in over a year and am not sure :)
