### ISSUE TITLE
Running `rails test` with JUnitTestReporter doesn't generate a file

### ISSUE THREAD

**Issue by joegaudet** [minitest-reporters/minitest-reporters#298]
When I run the following:

```rails test test/some-test.rb```

Everything works as expected.

When I run:

```rails test``` 

No file is generated in test/reports.

```
require 'minitest/reporters'
Minitest::Reporters.use!(
  [Minitest::Reporters::SpecReporter.new(color: true), Minitest::Reporters::JUnitReporter.new(single_file: true)],
  ENV,
  Minitest.backtrace_filter
)
```

Using minitest 1.4.2

**Comment by joegaudet** [comment]
Seems to work if I run a small folder as well, this is all very unclear

**Comment by barrettkingram** [comment]
This issue is pretty old, and I'm not able to reproduce. I will close for now, but I'm happy to take another look if this is still an issue and reproduction steps can be provided.
