### ISSUE TITLE
Is there a way to list all the failing tests at the bottom/end of the report?

### ISSUE THREAD

**Issue by duarme** [minitest-reporters/minitest-reporters#304]
We're now running Minitest with a fairly large test suite. When a test fails it's getting more and more inconvenient to track down which one it was, in order to fix it. It would be great if we could have only the **failing tests reported again at the bottom**. Is there any way to currently do that please?

Otherwise, this approach seems promising: https://stackoverflow.com/questions/63517155/minitest-how-to-see-the-failed-tests/63525669#63525669

**Comment by barrettkingram** [comment]
This is now possible with our `SpecReporter`! 

You can use the `print_failure_summary` option:
```ruby
Minitest::Reporters::SpecReporter.new(print_failure_summary: true)
```

[Documentation](https://www.rubydoc.info/gems/minitest-reporters/Minitest/Reporters/SpecReporter#initialize-instance_method)
