### ISSUE TITLE
Test suite stops/rescues when there is an error

### ISSUE THREAD

**Issue by Pifoupif** [minitest-reporters/minitest-reporters#319]
When I launch `rails test` in my terminal I can see all the PASS tests. 

But for each of the failed tests my terminal creates a pry session with a breakpoint. And it does not display the tests names that were FAIL.  

I want to kill this behavior, so not start a pry session, and see which test name FAIL. 

Does any one have idea where this pry session might be coming from ? (I don't think it's the default behavior right ?) And how I can remove this ?

**Comment by barrettkingram** [comment]
This sounds like behavior coming from some other gem, maybe [pry-rescue](https://github.com/ConradIrwin/pry-rescue)?
