### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by clarkedb** [minitest-reporters/minitest-reporters#321]
Is there a plan to support Ruby 3.0.x in a future release of `minitest-reporters` given that `minitest` supports Ruby 3.0 on most operating systems? Or is there already support that I just didn't see in the documentation?

**Comment by itsliamegan** [comment]
Is there an issue you're running into using `minitest-reporters` with Ruby 3.x?

**Comment by clarkedb** [comment]
> Is there a specific issue you're running into using `minitest-reporters` with Ruby 3.x?

No, I just wasn't able to verify from the docs that it should work and wasn't able to test it in the main app I'm working on. I set up a new ruby project and tested it there though. Just verified that it was working as expected on Ruby 3.02 and Ruby 3.1.0.
