### ISSUE TITLE
Replacement for TravisCI

### ISSUE THREAD

**Issue by andyw8** [minitest-reporters/minitest-reporters#322]
As per the notice on https://travis-ci.org/github/kern/minitest-reporters/

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. 

Does it make sense migrate to GitHub Actions?

**Comment by petergoldstein** [comment]
Here's a PR that does that - https://github.com/minitest-reporters/minitest-reporters/pull/324

**Comment by os97673** [comment]
merged
