### ISSUE TITLE
JUnitReporter breaks seed output

### ISSUE THREAD

**Issue by mikevoets** [minitest-reporters/minitest-reporters#341]
## Overview
We have a problem with the "# Running tests with run options --seed xxxx:" not outputting when we run the tests with a JUnitReporter.

## Repro steps
```ruby
# In test helper
reporters = [Minitest::Reporters::DefaultReporter.new(color: true)]
reporters << Minitest::Reporters::JUnitReporter.new('test/reports', true, { single_file: true })
Minitest::Reporters.use!(reporters)

# Run test suite 
bundle exec rails test
```

## Expected behaviour
"# Running tests with run options --seed xxxx:" is outputted to stdout when we run the tests.

## Actual behaviour
We don't get such output.

## Note
When we omit the JUnitReporter, we see the expected behaviour.

**Comment by barrettkingram** [comment]
Thanks for reporting!

Unfortunately, I'm not able to reproduce this behavior in my test application. The "# Running tests with run options --seed xxxx:" lines shows up fine for me using the exact same configuration of reporters you're using. Are you able to provide a script or sample app to help me reproduce this?

**Comment by mikevoets** [comment]
Sorry, I wasn't able to reproduce it anymore either. So let's forget about this 😊
